import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ReactQueryProvider } from '@/providers/ReactQueryProvider'
import { ChakraComponentProvider } from '@/providers/ChakraProvider'
import Navbar from '@/components/shared/navbar'
import Footer from '@/components/shared/footer'
import NextAuthProvider from '@/providers/NextAuthProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ReactQueryProvider>
      <NextAuthProvider>
        <html lang="en">
          <body className={inter.className}>
            <ChakraComponentProvider>
              <Navbar />
              {children}
              <Footer />
            </ChakraComponentProvider>
          </body>
        </html>
      </NextAuthProvider>
    </ReactQueryProvider>
  )
}
